service: localstack-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  
  # endpoint: http://localhost:4566 # Endpoint của LocalStack
  # environment:
  #     SQS_URL: ${self:resources.Resources.MyQueue.Properties.QueueUrl}

functions:
  sendMessage:
    handler: handler.sendMessage
    environment:
      SQS_URL:
        Fn::GetAtt:
          - MyQueue
          - QueueUrl
    events:
      - http:
          path: send-message
          method: post

resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-queue
